import '@/app/globals.css'

import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import type { ReactNode } from 'react'

import { getTheme } from '@/actions/cookies'
import { Toaster } from '@/components/ui/sonner'
import { fontSans } from '@/configs/font'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type LocaleLayoutProps = Readonly<{
  children: ReactNode
  params: { locale: string }
}>

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  const theme = getTheme()
  const messages = useMessages()

  return (
    <html lang={locale} className={theme}>
      <body
        className={cn(
          'min-h-screen bg-base font-sans antialiased',
          fontSans.variable,
        )}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <main>{children}</main>
        </NextIntlClientProvider>
        <Toaster theme={theme} position="top-center" richColors />
      </body>
    </html>
  )
}
